defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5


development:
  adapter: mysql2
  database: butaca_dev
  username: root
  password: 1234
  encoding: utf8
  reconnect: false
  pool: 5

production:
  adapter: mysql2
  database: butaca_dev
  username: root
  password: 1234
  encoding: utf8
  reconnect: false
  pool: 5
